### ISSUE TITLE
Stopping condition for SVD

### ISSUE THREAD

**Issue by adideshp** [aaw/IncrementalSVD.jl#11]
Hi,
      I am unable to understand the stopping criteria for breaking from epoch during factor computation (https://github.com/aaw/IncrementalSVD.jl/blob/master/src/train.jl#L40). As far as I understood it, you are trying to find a point in the curve which has error less than the previous error and previous error greater than the one before, but I don't understand why.

Shouldnt the condition be, 
`if errors[0] > errors[1]` 

Thanks

**Comment by aaw** [comment]
The stopping criteria I used is the best I found for maximizing RMSE on the datasets I tested with. If errors[0] > errors[1] works for you then by all means use that instead.
