### ISSUE TITLE
ArgumentError: premature end of integer: ""

### ISSUE THREAD

**Issue by BeenKimAI2** [aaw/IncrementalSVD.jl#4]
Anyone had this issue? Seems like some parsing function in Julia is generating this

https://github.com/JuliaLang/julia/blob/master/base/parse.jl

If it's a version issue, which version of Julia would work smoothly with IncrementalSVD?

julia> rating_set = IncrementalSVD.load_small_movielens_dataset();
Downloading movie ratings data...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5778k  100 5778k    0     0  1106k      0  0:00:05  0:00:05 --:--:-- 1324k
Extracting movie data...
Archive:  /var/folders/w8/4yk15w79117b7zkz049r74dh0000gp/T/ml-1m.zip
  inflating: /var/folders/w8/4yk15w79117b7zkz049r74dh0000gp/T/ml-1m/movies.dat  
Extracting ratings data...
Archive:  /var/folders/w8/4yk15w79117b7zkz049r74dh0000gp/T/ml-1m.zip
  inflating: /var/folders/w8/4yk15w79117b7zkz049r74dh0000gp/T/ml-1m/ratings.dat  
ERROR: ArgumentError: premature end of integer: ""
 in tryparse_internal at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib (repeats 2 times)
 in parse at parse.jl:146
 in load_movielens_dataset at /Users/beenk/.julia/v0.4/IncrementalSVD/src/movielens_dataset.jl:30
 in load_small_movielens_dataset at /Users/beenk/.julia/v0.4/IncrementalSVD/src/movielens_dataset.jl:65

**Comment by aaw** [comment]
Looks like that line is shelling out to `wc` and you're running on Windows, which doesn't have `wc`. If you want to submit a patch that uses Julia's `countlines` instead of shelling out to `wc` in the 4 or so places we do it in this repo I'd be glad to merge that in.

**Comment by BeenKimAI2** [comment]
I am not running windows, but Mac. I do have wc..

**Comment by aaw** [comment]
Sorry, I should have read your backtrace more carefully. The code you're hitting works for me on Linux with Julia 0.4.3, so again, I think the best fix is using `countlines` instead.

**Comment by BeenKimAI2** [comment]
Hi aaw!

I've temporarily fixed the problem by changing line 30 in movielens_dataset.jl to:

movie_count = parse(Int, split(readall(`wc -l $(movie_file_name)`), " ")[5])

and line 42 to:

ratings_count = parse(Int, split(readall(`wc -l $(ratings_file_name)`), " ")[2])      

And all works. 

I do not think this would be a general solution for everyone nor an elegant one, so  I don't think I'll submit a patch. But I leave it here in case anyone run into the same issue. 

Thanks for your help!
