### ISSUE TITLE
Number of users and movies are different from the data?

### ISSUE THREAD

**Issue by BeenKimAI2** [aaw/IncrementalSVD.jl#6]
Hi, 

In Readme, it indicates that there are 6000 users and 4000 movies in the small movielens data. But When I follow the exact steps you've described in the Readme, I get 3706 movies and 6040 users. I get these numbers from the rows of model.V and model.U matrices,  as well as model.item_to_index.

Any insights would be helpful. Thanks!

**Comment by aaw** [comment]
The numbers quoted in the README are likely estimates
